name: test

on:
  workflow_dispatch:

jobs:
  test:
    name: test vault test
    environment: test
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
      id-token: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      # - name: Debug Vault Token
      #   run: |
      #       curl -sSL -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=$VAULT_AUDIENCE" | \
      #       jq "{ jwt: .value, role: \"$VAULT_ROLE\" }" > ./token.json
            
      #       echo 'GitHub Actions Token Claims'
      #       cat ./token.json | jq -r '.jwt | split(".") | .[1] | @base64d' | jq

      #       echo 'Vault Login Response'
      #       curl -sSLf -X POST -H "Content-Type: application/json" --data @token.json $VAULT_URL/v1/auth/$VAULT_AUTH_PATH/login

      #       # Remove the token file when we're done (if we don't fail)
      #       rm ./token.json
      #   env:
      #       VAULT_URL: https://vault.fen4o.com
      #       VAULT_AUDIENCE: https://vault.fen4o.com
      #       VAULT_AUTH_PATH: github
      #       VAULT_ROLE: test-github-actions-key-reader
      - name: Vault
        uses: hashicorp/vault-action@v2.7.0
        id: secrets
        with:
          url: https://vault.fen4o.com
          jwtGithubAudience: https://vault.fen4o.com
          role: github-actions-test
          method: jwt
          path: github
          jwtTtl: 60
          secrets: |
            test/data/foo/bar foo;
            test/data/muu/gaz bbaaa;
